export const options = [
    { value: 1, label: 'Electronics' },
    { value: 2, label: 'Appliances' },
    { value: 3, label: 'Cloth' },
    { value: 4, label: 'Shoes' },
    { value: 5, label: 'Accessories' },
    { value: 6, label: 'Beauty' },
    { value: 7, label: 'Health' },
    { value: 8, label: 'Household products' },
    { value: 9, label: 'Construction and repair' },
    { value: 10, label: 'Automotive products' },
    { value: 11, label: "Children's goods" },
    { value: 12, label: 'Hobbies and creativity' },
    { value: 13, label: 'Sports and recreation' },
    { value: 14, label: 'Food' },
    { value: 15, label: 'Personal hygiene' },
    { value: 16, label: 'Stationery' },
    { value: 17, label: 'Pet supplies' },
    { value: 18, label: 'Books' },
    { value: 19, label: 'Vacancy' },
    { value: 20, label: 'Other' },
]